# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

demo = User.create(email: "demo_user@infinote.com", password: "infinote", username: "DemoUser")
user1 = User.create(email: "test@test.com", password: "password")

notebook1 = Notebook.create(title: "The Uranium Bull Market Thesis", author_id: 1)
notebook2 = Notebook.create(title: "My First Notebook", author_id: 1)
notebook3 = Notebook.create(title: "Housing Options", author_id: 1)
notebook4 = Notebook.create(title: "Budget", author_id: 1)
notebook5 = Notebook.create(title: "Predicting the Next Market Crash", author_id: 1)


main_notebook = Notebook.create(title: "My First Notebook", author_id: 2)
notebook1 = Notebook.create(title: "Housing Options", author_id: 2)
notebook2 = Notebook.create(title: "Budget", author_id: 2)

Note.create(title: "The opportunities are infinite!", content: "In infiNote, you can create, render, update, and delete notes!", author_id: 1, notebook_id: 2 )
Note.create(title: "Notes without a notebook will be grouped, and displayed here!", content: "You can move notes around, update them, delete them, all whenever you please", author_id: 1 )

Note.create(title:"Reasons to Buy Property", content: "Unlike cars, houses are generally not depreciating assets. Unless, of course you happen to live in upstate New York or Western Pennsylvania", author_id: 1, notebook_id: 3)
Note.create(title:"Reasons to NOT Buy Property", content: "Mortgages can be a financial burden, and many Americans live in debt because they are unable to pay for their own housing costs. Additionally, you have a sense of responsibility and commitment to the house, meaning that you are relatively inflexible with regards to moving.", author_id: 1, notebook_id: 3)
Note.create(title:"How to Budget", content: "Step 1: Have money...", author_id: 1, notebook_id: 4)

Note.create(title:"Background", content: '
Background and Previous Bull Run
In 2007, uranium’s last major bull run, Cameco’s ($CCJ) Cigar Lake mine was subject to flooding. Being one of the world’s largest suppliers, this ‘fear’ of a supply deficit created a bull market that saw uranium’s per pound price explode from around $36 to $140 at the start of June 2007. Considering that the extraction price for an average miner is around 40–50$/lb, they were flooded by cash flows and they went from being penny stocks to extremely profitable companies.
There are currently 442 nuclear reactors operating in 30 countries, the main being: US (95), France (57), China (47), Russia (38), Japan (33). Together these reactors consume around 200 million pounds of uranium per year. Furthermore, there are over 50 reactors under construction and an additional 321 reactors proposed.
The current supply deficit is about 20 million pounds and could reach as much as 50 million pounds as mine production has been suspended due to COVID-19.
Therefore, prices have to rise to at least 50–60 $/lb, or nations like the US, with more than 20% of energy generated by nuclear reactors will leave their population without energy, i.e. California’s recent rolling blackouts' ,author_id: 1, notebook_id: 1)
Note.create(title:'Supply Contraints'  , content:'
Supply Constraints
The following by URNMETF illustrates the Supply Constraints which may soon give way to higher prices in the uranium market.
https://www.urnmetf.com/posts/supply-constraints-may-drive-uranium
Utilities Underbuying Uranium
Utilities have been underbuying uranium since 2014 — they have been buying less uranium than they need to produce nuclear energy. The deficit, or the difference between what they are buying and the amount they need to produce nuclear energy, has been filled by the drawdown of existing inventories.
Leading to Drawdown of Inventories
US inventories of uranium have been drawn down 30% over the last twelve months. These leaves US utilities with around 2.5 years of inventory. Given the long lead time required for uranium delivery, utilities have historically not let their inventories fall below the 2–3-year coverage level. As such, utilities may need to start entering the market to secure more uranium, even before increases to nuclear generation capacity.
At the Same Time That Production Has Shut Down
In response to lower prices, major uranium producers began cutting capacity over the past several years. These cuts have been accelerated by the recent coronavirus pandemic, forcing more producers to close down mining operations.
- We have also seen BHP scrapping its Olympic Dam expansion and 3 Ukraine mines being suspended due to insolvency.
- China’s CGN announced their buying of 49% interest in 2 big uranium mines from Kazatomprom taking out 3.5 mibs/year from the market.
- In January 2021, Australia’s Ranger mine will closed permanently and Niger’s COMINAK mine will close in March. Both mines will close due to ore depletion after decades of mining taking out another 6 mlbs/year.
' ,author_id: 1, notebook_id: 1)
Note.create(title: "Reason for Current Lull" , content: "
Low Prices Hindering Long-Term Contracts
Historically, utilities have secured uranium for their operation through long-term (generally 10-year) contracts with miners. However, no major contracting activity has occurred since the Fukushima incident in 2011. As a result, many of these contracts will begin expiring next year, resulting in large, uncovered uranium demand.
Utilities, however, are unwilling to enter into long-term contracts at today’s low prices. It is estimated that uranium prices would have to double just to reach the cost of production and entice miners and producers to reopen capacity and begin entering into contracts
Elon Musk endorsing Nuclear
Recently, nuclear energy has been getting a lot of positive attention, the most notable from Elon (www.youtube.com/watch?v=bKH-uVqg9OI)
Related Pro-nuclear arguments:
1. Provide baseload energy around the clock — essential to the implementation of Electric Vehicles
2. Power outages in Cali due to unreliable renewable energy sources of wind and solar will be amplified by the implementation of laws banning the use of gas vehicles… i.e. what happens in 2025 when everyone tries to charge their car at 6pm?
3. It can provide carbon-free, constant, CHEAP electricity" ,author_id: 1, notebook_id: 1)
Note.create(title: "Case Study: Japan" , content:'
CASE STUDY: JAPAN
“Japan is suffering its worst energy crisis since the 2011 Fukushima nuclear disaster, with very tight supply of both electricity and natural gas. Domestic wholesale electricity prices have spiked to a record high”
“the price of wholesale electricity spike from about 13 cents per kilowatt-hour in December to an unprecedented peak of more than $1 on Jan. 7.”
' ,author_id: 1, notebook_id: 1)

Note.create(title:'Commodities vs. Equity Ratio' , content: '
Commodities vs. Equity Ratio
This is ready for a correction; commodities have never been cheaper relative to equities. Currently there are many of the best resource companies available at incredible valuations.
Uranium Spot Price
Most nuclear power operators buy uranium on a long-term contract basis, with only about 10 per cent of supply sold on a spot basis.
But it is the spot market that determines the direction of contract prices, and sooner or later power companies will have to pay more for uranium as spot prices rise and contracts expire.
Thus, most uranium miners have placed their mines on care and maintenance ($PDN.AX, $CCJ, etc…). The current capacity, mostly coming from the largest four uranium producers, will not be enough to cover future demand requirements. Thus, utilities will search for supply from smaller producers. Even mines in care and maintenance could take around 18 months to return to full production.
The uranium market is burning through excess uranium supply, mostly coming from the spot market. Within the next 2.5 years, it is highly likely demand for uranium will outstrip supply. To secure supply, utilities need to contract uranium at higher prices than the current price.
Power companies with nuclear plants have taken a complacent view on supply levels, and have not seen any urgency to increase their uranium stocks.
When utilities realise that supply cannot easily be added to the uranium market, they are likely to rush into the market and drive up prices.
More mine shutdowns anticipated over next 5–10 years, depressed uranium prices have resulted in a significant decline in investment in exploration which is impacting development of potential new mines' ,author_id: 1, notebook_id: 1 )

Note.create(title: "Zero Carbon Energy Sources" , content:'
Zero-Carbon Energy Sources
If you truly want to cut carbon-emission in the atmosphere, the one way to do it and that’s via nuclear. Ask @isaboemeke about this.
For example, take Germany vs. France. Despite its massive efforts towards renewability, it is one of the worst carbon emitting countries in Europe. France currently emits 71g of CO2 eq/kWh, while Germany emits 441g.    
As well as this, there are unforeseen issues with solar; recycling the heavy metals is going to be an issue in 15/20 years, and solar on a mass scale is not sustainable' ,author_id: 1, notebook_id: 1 )

Note.create(title: "John Quake’s 15 ‘First Time’ catalysts:
", content: "1. First time entering a new year with uranium already in a record supply deficit, which is set to deepen further with 2 major mines permanently closing this year in Australia and Niger (~7 million pounds, gone). At the same time, demand for nuclear energy has remained strong throughout the COVID-19 pandemic and continues to grow in a global shift to decarbonize industry dependent on fossil fuels.
2. First time that Cameco, the world’s 2nd largest producer, has begun a new year with every one of its uranium mines in Canada shut down. Both of the world’s 2 largest uranium mines are under care and maintenance, resulting in zero lbs being produced in Canada as we enter 2021. The US is also producing zero lbs while Kazakhstan’s production is at a multi-year low that is likely to continue thru 2022 under the nation’s current flex-down program and pandemic related mining disruptions. All uranium mines in the Ukraine have also been shut down due to the inability of the mine operator to pay the wages of 5000 mine workers.
3. First time that at least 3 of the world’s largest uranium producers are forced into buying uranium on the spot market. Cameco is now the largest spot market buyer in the world. World’s largest producer Kazatomprom is now also a spot buyer, as is French Orano given that heir Canadian mills are suspended and their Cominak mine in Africa is heading for closure in March. Inventory held by the world’s largest uranium producers is at rock bottom levels for the first time ever and in need of replenishment this year.
4. First time the US has taken steps to support its domestic uranium mining industry by establishing a strategic uranium reserve, a 10 year buying program (1.5 billion dollars total) whereby the US government will purchase, convert and potentially enrich US mined uranium to create an emergency supply for US reactors. Goal is to ensure at least 2 US uranium mining companies remain active and viable during this time when the commodity price of U3O8 is half the cost of production.
5. First time in several decades that there is strong bipartisan support in the US to rebuild the existing nuclear energy industry and manufacture a new generation of advanced reactors on a global scale, which is seen as a high priority in order to catch up with Russia and China who have become the new world leaders in nuclear energy.
6. First time that uranium equities have entered a bull market when there is an actual supply deficit. The last bull market saw the price of uranium skyrocket on mine floods and other events that created the ‘fear’ of a supply deficit on the horizon, at a time when the US-Russia Megatons to Megawatts program was still continuing to supply 20m lbs per year to US nuclear utilities, a program that continued until 2021 as the world’s largest virtual uranium mine.
7. First time that a new year begins with spot market supplies significantly depleted. Supply accessible to carry traders has been severely reduced. Kazatomprom no longer sells any lbs into the spot market and Orano’s supply from Canada and Niger is at a record low level, pushing nuclear utilities to secure new long term contracts with producers rather than entering into shorter term contracts with carry traders. Security of supply is a top priority of utilities (whose inventories are estimated to be around 2,5 years’ worth of supply, when the guideline is to never let it drop below 2–3 years given the long time it takes to enrich and deliver the fuel to the reactors).
8. First time that US and European nuclear utilities have begun a new year with inventories drawn down below usual safety margins at the same time that mines supply is in a record deficit and global uranium production is at its lowest level in 12 years. The new 2020 IAEA/NEA uranium Red Book projects that secondary supplies will fall in the future as an overdue utility inventory restocking cycle begins, due to higher levels of contracting, conversion and enrichment that will reduce underfeeding as facilities see their utilization rates rise.
9. First time in several years that there are no geopolitical overhangs holding back the uranium contracting plans of US and European nuclear utilities. There are no potential section 232 actions targeting uranium imports and no sanctions likely against UUN participants (Russia, China, UK, Germany, France) in the JCPOA Iran Nuclear deal. Russia and the US have successfully negotiated a 20-year extension to the Russian Suspension Agreement that will see the US imports from Russia decline over the coming 2 decades. The incoming US administration supports keeping nuclear power plants running and plans to immediately rejoin the Paris Climate Accord, pushing for global net zero emissions by 2050, a process in which nuclear energy will play a major role.
10. First time that nations around the world will be recovering from a global pandemic with massive infrastructure spending programs that include boosting nuclear capacity to achieve net zero carbon emissions goals. A new ‘nuclear renaissance’ is beginning to take shape on pandemic recovery spending to boost clean energy. The perception of nuclear energy is also changing to that of a safe, reliable, necessary baseload power source that fits with an emerging ESG investing model. Decarbonization has become a new buzz word in the global vocabulary. The ‘electrification of everything’ from cars, buses, trucks and trains to major industry is the new global target. Sustainability of so-called renewables solar and wind is now being called into question after failures by Germany and California to successfully transition to an economy powered by intermittent energy sources. Higher electricity prices, no net carbon emissions reductions and rolling blackouts have demonstrated how ‘renewables’ are not able to fulfill their early promise. This might change with new battery technology and better implementation, but we are nowhere near that point yet.
11. First time that uranium stocks are entering a new year on the heels of one of their best performance years since the last bull market. The U3O8 spot price is still one-half the global average cost of production that will incentivize new mines to be built this decade. This signals to investors that we are still at the opening pitch of the first inning of a long game yet to play out. A necessary doubling of the U3O8 commodity price is yet to come.
12. First time that Canada has begun a new year embarking on a small modular reactors build-out program with several provinces pledging to deploy SMR’s to power remote communities, mines and industrial heat applications in the energy industry.
13. First time that nuclear is being viewed as the ideal carbon free high-temperature power source to produce clear hydrogen fuel. US, Russia, Japan and others are looking to leverage their existing nuclear power capacity to produce hydrogen and build high-temperature SMR’s to optimize the use of emissions free nuclear to produce zero emissions hydrogen.
14. First time in decades that there is an emerging surge in acceptance of nuclear of nuclear energy as necessary to achieve zero carbon emissions goals, with countries like the Netherlands looking to add more capacity after conducting studies showing nuclear is safer and cheaper than variable renewable energy.
15. First time I can recall one of the leading nuclear fuel consultants UxC reporting to their subscribers that uranium is in a 57M lbs mined supply deficit, that utility and supplier inventories are “declining at a rapid rate” just as global fuel demand growth is accelerating, a clear signal that a bull market is getting underway.", author_id: 1, notebook_id: 1 )
Note.create(title: "References", content: "
Author: @awgejocoU308,
Author Blog: https://josephcollinsul.medium.com/the-uranium-bull-thesis-ce6d49ebd219
", author_id: 1, notebook_id: 1)